export const ENGLISHWORDS = {
  titlePage: "Inscription",
  name: "Name",
  classLevel: "class",
  prename: "Prename",
  birthDate: "Birthday",
  sex: "Sex",
  uniformBooks: "Uniform Books",
  vaccination: "Vaccination",
  guardian: "Guardian",
  studentId: "Student ID",
  phoneNumber: "Phone Number",
  placeOfBirth: "Place Of Birht",
  registerFees: "Register Fees",
  monthlyPayment: "Monthly Payment",
  beginMonthPay: "Beginning Monthly Payment",
};
export const FRENCHWORDS = {
  titlePage: "Une Inscription",
  name: "Nom",
  classLevel: "classe",
  prename: "Prenom",
  birthDate: "Date de Naissance",
  sex: "Sexe",
  uniformBooks: "Livres Unifomes",
  vaccination: "Vaccination",
  guardian: "Tuteur",
  studentId: "Etudiant ID",
  phoneNumber: "Telephone",
  placeOfBirth: "Liew de Naissance",
  registerFees: "Frais Inscription",
  monthlyPayment: "Mensualite",
  beginMonthPay: "Debut de Mensualite",
};
export const PORTOWORDS = {
  titlePage: "Inscrição",
  name: "Nome",
  classLevel: "Aula",
  prename: "Primeiro Nome",
  birthDate: "Data de nascimento",
  sex: "Sexo",
  uniformBooks: "Livros Uniformes",
  vaccination: "Vacinação",
  guardian: "Tutor",
  studentId: "Identidade Estudantil",
  phoneNumber: "Telefone",
  placeOfBirth: "Liew do Nascimento",
  registerFees: "Registrar Taxas",
  monthlyPayment: "Pagamento Mensal",
  beginMonthPay: "Início do pagamento mensal",
};
